### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by gzsombor** [floneum/floneum#66]
I've tried to run with `cargo run --release`,
however it crashes instantly:
```
thread 'main' panicked at 'GTK has not been initialized. Call `gtk::init` first.', /home/zsombor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.16.2/src/auto/menu_item.rs:56:9
stack backtrace:
   0:     0x55ebbf5169cf - std::backtrace_rs::backtrace::libunwind::trace::h782cc21a5acaf6cb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ebbf5169cf - std::backtrace_rs::backtrace::trace_unsynchronized::hc579eb24ab204515
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ebbf5169cf - std::sys_common::backtrace::_print_fmt::h7223525cfdbacda2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ebbf5169cf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ebbeedb19f - core::fmt::rt::Argument::fmt::hb4f4a02b9bd9dd49
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:     0x55ebbeedb19f - core::fmt::write::h6d54cd7c9e155ec5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:     0x55ebbf4e6cc0 - std::io::Write::write_fmt::h6a453a71c692f63b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:     0x55ebbf5182ff - std::sys_common::backtrace::_print::h1cbaa8b42678f928
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55ebbf5182ff - std::sys_common::backtrace::print::h4ddf81241a51b337
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55ebbf517b85 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
  10:     0x55ebbf518a94 - std::panicking::default_hook::h21f14afd59f7aef9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:     0x55ebbf518a94 - std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:     0x55ebbf518553 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
  13:     0x55ebbf5184e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55ebbf5184d1 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:     0x55ebbed86ce2 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:     0x55ebbf0d6875 - gtk::auto::menu_item::MenuItem::with_mnemonic::h0688816215ec2f0a
  17:     0x55ebbf5249b3 - tao::menu::MenuBar::add_item::h5128a97673f7ef65
  18:     0x55ebbee788e6 - floneum::main::{{closure}}::h2338f1b7d5a080f8
  19:     0x55ebbee77c10 - floneum::main::he651d00b74f40c4b
  20:     0x55ebbee04ef0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h61125b8ff671c428
  21:     0x55ebbee7c0e6 - main
  22:     0x7f81b4204d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23:     0x7f81b4204e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  24:     0x55ebbedbafa5 - _start
```

**Comment by ealmloff** [comment]
This may be related to https://github.com/tauri-apps/wry/pull/708#issuecomment-1263730033
